import { ArrowRight, Check, ShieldCheck, ExternalLink, FlaskConical } from 'lucide-react';
import { Badge, KeyValue, SourceLink } from './primitives';
import { data, byId, related, relationById, modelProofs, instrumentName, price, windowLabel, emergencyLabel, expressionFor, structuralChecks } from '../domain/engine';

export function RelationshipInspector({ id, onInstrument, onScenario }: { id: string; onInstrument: (id: string) => void; onScenario: () => void }) {
  const r = relationById[id];
  const check = structuralChecks().find(c => c.id === id);
  return <div className="inspector"><div className="eyebrow">RELATIONSHIP INSPECTOR <span>/ {r.domain.replaceAll('_', ' ')}</span></div><div className="inspector-heading"><h2>{r.label === 'EXPECTATION_BOUND' ? 'A bound, backed by structure.' : r.label === 'PARTITION' ? 'Every state. Exactly one outcome.' : 'One claim implies another.'}</h2><Badge tone="teal">EXACT · DEMO MODEL</Badge></div>
    <p className="inspector-description">{r.description}</p><div className="expression"><span>PAYOFF CONSTRAINT</span><code>{r.expression}</code></div>
    <div className="verification"><ShieldCheck size={18}/><div><strong>{modelProofs[id] ? 'Deterministically verified' : 'Verification failed'}</strong><span>{modelProofs[id] ? 'Holds across all 350 representative demo trajectories.' : 'This relationship does not hold in the model.'}</span></div></div>
    <div className="detail-section"><h3>Participating instruments</h3>{r.ids.map(instrument => <button key={instrument} className="instrument-link" onClick={() => onInstrument(instrument)}><div><span>{instrumentName(instrument)}</span><small>{instrument}</small></div><span className="mono">{price(byId[instrument].snapshot_mark)}</span><ArrowRight size={14}/></button>)}</div>
    {check && <div className="snapshot-equation"><div><span>Snapshot {check.kind === 'STRUCTURAL RESIDUAL' ? 'sum' : 'left side'}</span><strong>{(check.lhs * 100).toFixed(1)}¢</strong></div><span>−</span><div><span>{check.kind === 'STRUCTURAL RESIDUAL' ? 'Partition target' : 'Derived bound'}</span><strong>{(check.rhs * 100).toFixed(1)}¢</strong></div><span>=</span><div><span>{check.kind.toLowerCase()}</span><strong className={check.kind === 'STRUCTURAL RESIDUAL' ? 'amber-text' : 'positive'}>{check.delta.toFixed(1)} pp</strong></div></div>}
    <div className="detail-section"><h3>Proof & scope</h3><KeyValue label="Direction">{r.label === 'PARTITION' ? 'Exhaustive, mutually exclusive collection' : r.label === 'EXPECTATION_BOUND' ? 'Left side dominates the combined right side' : 'Left side → right side; reverse not asserted'}</KeyValue><KeyValue label="Method">Payoff evaluation / finite state enumeration</KeyValue><KeyValue label="Local state space"><code>{r.basis}</code></KeyValue><KeyValue label="Source admission">Rules reviewed for the supplied demo fixture</KeyValue><KeyValue label="Proof scope">Compiled model, not automated source interpretation</KeyValue></div>
    {r.consequence && <div className="note"><strong>Expectation consequence</strong><code>{r.consequence}</code><p>Valid under a common probability measure and compatible settlement assumptions. Independently quoted venue marks can differ; this is a structural check, not an executable trade.</p></div>}
    {r.counterexample && <div className="note amber"><strong>The reverse fails</strong><p>{r.counterexample}</p><code>Another Hike = 0 · Count 1 = 0</code><button className="text-button" onClick={onScenario}>Load the counterexample <FlaskConical size={14}/></button></div>}
    {id === 'con_eoy425_implies_hit425' && <div className="note amber"><strong>A path is not a terminal state</strong><p>October +25 bp followed by December −25 bp reaches 4.25%, then returns to 4.00%. Hit ≥4.25 pays YES; EOY 4.25 pays NO.</p></div>}
    {id === 'con_hit450_implies_hit425' && <div className="note"><strong>Thresholds, not exact hits</strong><p>Reaching 4.50% or higher necessarily reaches the 4.25%-or-higher threshold. Reaching 4.25% alone does not imply 4.50%.</p></div>}
  </div>;
}
export function InstrumentInspector({ id, onRelationship }: { id: string; onRelationship: (id: string) => void }) {
  const i = byId[id], event = data.source_events.find(e => e.event_id === i.event_id)!;
  return <div className="inspector"><div className="eyebrow">INSTRUMENT INSPECTOR <span>/ VERSION {i.version}</span></div><h2>{instrumentName(id)}</h2><div className="instrument-meta"><Badge>POLYMARKET</Badge><Badge tone="teal"><Check size={11}/> REVIEWED FOR DEMO</Badge><span className="mono">{price(i.snapshot_mark)} YES</span></div>
    <section className="layer"><div className="layer-index">01</div><div><h3>Venue contract</h3><h4>{event.title}</h4><p>{event.rules_summary}</p><SourceLink url={i.source_url}/><KeyValue label="Resolution window">{windowLabel(i)}</KeyValue><KeyValue label="Emergency treatment">{emergencyLabel(i)}</KeyValue><KeyValue label="Observation source">Federal Reserve target federal funds upper bound</KeyValue><KeyValue label="Source provenance">Supplied Sep 21 snapshot · event rule summary</KeyValue></div></section>
    <section className="layer"><div className="layer-index">02</div><div><h3>Canonical claim</h3><p>{i.canonical_question}</p><pre>{JSON.stringify(i.claim, null, 2)}</pre><div className="quiet-copy">AI-assisted extraction proposes a claim. Source admission and deterministic validation are separate steps.</div></div></section>
    <section className="layer"><div className="layer-index">03</div><div><h3>Payoff expression</h3><div className="expression"><code>{expressionFor(id)}</code></div><KeyValue label="Settlement">YES: $1 if true, $0 otherwise · NO: complement</KeyValue><KeyValue label="Family"><code>{i.family_id}</code></KeyValue></div></section>
    <section className="layer"><div className="layer-index">04</div><div><h3>Structural relationships <span className="panel-count">{related(id).length}</span></h3>{related(id).map(r => <button className="relationship-link" key={r.id} onClick={() => onRelationship(r.id)}><Badge tone="teal">{r.label.replaceAll('_', ' ')}</Badge><code>{r.expression}</code><ExternalLink size={13}/></button>)}</div></section>
  </div>;
}
