import { Search, ArrowUpRight, SlidersHorizontal, RotateCcw } from 'lucide-react';
import { useState } from 'react';
import { Panel, Badge } from './primitives';
import { data, familyName, instrumentName, price, related, windowLabel, emergencyLabel } from '../domain/engine';

export function InstrumentMaster({ query, setQuery, onInstrument }: { query: string; setQuery: (s: string) => void; onInstrument: (id: string) => void }) {
  const [family, setFamily] = useState('all'), [relation, setRelation] = useState('all'), [window, setWindow] = useState('all');
  const items = data.instruments.filter(i => `${i.short_name} ${i.canonical_question} ${i.instrument_id} ${instrumentName(i.instrument_id)}`.toLowerCase().includes(query.toLowerCase()) && (family === 'all' || i.family_id === family) && (relation === 'all' || related(i.instrument_id).some(r => r.label === relation)) && (window === 'all' || windowLabel(i).includes(window)));
  return <Panel title="Canonical instrument universe" eyebrow={`${items.length} / ${data.instruments.length} CONTRACTS`}><div className="filter-bar"><label className="search-input"><Search size={15}/><input aria-label="Search instruments" placeholder="Search contracts, claims or identifiers…" value={query} onChange={e => setQuery(e.target.value)}/></label><SlidersHorizontal size={15} className="muted"/><select aria-label="Filter family" value={family} onChange={e => setFamily(e.target.value)}><option value="all">All families</option>{data.families.map(f => <option key={f.family_id} value={f.family_id}>{familyName(f.family_id)}</option>)}</select><select aria-label="Filter relationship" value={relation} onChange={e => setRelation(e.target.value)}><option value="all">All relationships</option><option value="IMPLIES">Implies</option><option value="PARTITION">Partition</option><option value="EXPECTATION_BOUND">Expectation bound</option></select><select aria-label="Filter resolution window" value={window} onChange={e => setWindow(e.target.value)}><option value="all">All windows</option><option value="Oct">October</option><option value="09 Dec">December meeting</option><option value="31 Dec">December 31</option></select><button className="icon-button" aria-label="Reset filters" onClick={() => { setQuery(''); setFamily('all'); setRelation('all'); setWindow('all'); }}><RotateCcw size={15}/></button></div><div className="universe-context"><Badge>POLYMARKET</Badge><Badge tone="teal">REVIEWED FOR DEMO</Badge><span>7 source events · 3 local families · preserved venue identity</span></div><div className="table-scroll"><table className="master-table"><thead><tr><th>Canonical instrument / venue event</th><th>Family</th><th>Metric</th><th>Condition</th><th>Resolution window</th><th>Emergency actions</th><th>YES mark</th><th>Links</th><th/></tr></thead><tbody>{items.map(i => <tr key={i.instrument_id}><td><button className="instrument-cell" onClick={() => onInstrument(i.instrument_id)}><strong>{instrumentName(i.instrument_id)}</strong><span>{data.source_events.find(e => e.event_id === i.event_id)?.title}</span></button></td><td>{familyName(i.family_id)}</td><td className="metric-column">{i.claim.predicate.metric.replaceAll('_', ' ')}</td><td className="mono">{i.claim.predicate.comparator === 'EQ' ? '=' : '≥'} {String(i.claim.predicate.value)}</td><td>{windowLabel(i)}</td><td>{emergencyLabel(i)}</td><td className="mono positive">{price(i.snapshot_mark)}</td><td className="mono">{related(i.instrument_id).length}</td><td><button className="icon-button" onClick={() => onInstrument(i.instrument_id)} aria-label={`Inspect ${i.short_name}`}><ArrowUpRight size={14}/></button></td></tr>)}</tbody></table>{items.length === 0 && <div className="empty-state"><Search size={26}/><h3>No matching instruments</h3><p>Try another contract or reset the filters.</p></div>}</div></Panel>;
}
