import { ArrowRight, ArrowUpRight, CheckCheck, Download, Layers3 } from 'lucide-react';
import { Panel, Badge } from './primitives';
import { RelationshipGraph } from './RelationshipGraph';
import { data, byId, presets, portfolio, instrumentName, familyName, sum, money, compact, price, sideMark, markPnl, related, structuralChecks } from '../domain/engine';

export function PortfolioWorkspace({ selected, onSelect, onInstrument, onRelationship, onScenario, onRelationships, graphVisible, checksVisible }: { selected: string; onSelect: (id: string) => void; onInstrument: (id: string) => void; onRelationship: (id: string) => void; onScenario: (index: number) => void; onRelationships: () => void; graphVisible: boolean; checksVisible: boolean }) {
  const positions = data.portfolio.positions;
  const results = presets.map(p => portfolio(p.state));
  const scenarioNames = ['Hike / Hike', 'Pause / Hike', 'Hike / Pause', 'Pause / Pause', 'Emergency hike', 'Hike / Cut'];
  const cost = sum(positions.map(p => p.quantity * p.entry_price)), unrealized = sum(positions.map(markPnl));
  const exportPortfolio = () => {
    const rows = ['instrument,side,quantity,entry,mark,cost,unrealized_pnl', ...positions.map(p => [p.instrument_id, p.side, p.quantity, p.entry_price, sideMark(p).toFixed(3), p.quantity * p.entry_price, markPnl(p)].join(','))];
    const url = URL.createObjectURL(new Blob([rows.join('\n')], { type: 'text/csv' })); const a = document.createElement('a'); a.href = url; a.download = 'axiom-portfolio-2026-09-21.csv'; a.click(); URL.revokeObjectURL(url);
  };
  return <><div className="summary-strip"><div><span>CAPITAL DEPLOYED</span><strong>{money(cost)}</strong><small>Fictional portfolio · USD</small></div><div><span>SNAPSHOT P&L</span><strong className="positive">{money(unrealized, true)}</strong><small>Mark to entry · before costs</small></div><div><span>LOWEST PRESET P&L</span><strong className="negative">{money(Math.min(...results.map(r => r.pnl)))}</strong><small>Among 6 curated scenarios</small></div><div><span>INSTRUMENT COVERAGE</span><strong>{positions.length}<i>/</i><em>{data.instruments.length}</em></strong><small>Held / normalized contracts</small></div><div className="summary-context"><Layers3 size={21}/><div><strong>One market. Multiple meanings.</strong><small>3 local state spaces · 1 linked scenario model</small></div></div></div>
  <div className={`portfolio-layout ${!graphVisible && !checksVisible ? 'single-column' : ''}`}><div className="primary-column"><Panel title="Positions" eyebrow={`${positions.length} INSTRUMENTS`} actions={<button className="text-button muted" onClick={exportPortfolio}><Download size={13}/> Export</button>}>
    <div className="table-scroll"><table className="positions-table"><thead><tr><th>Instrument</th><th>Side</th><th>Quantity</th><th>Entry</th><th>Mark</th><th>Cost</th><th>Unrealized P&L</th><th aria-label="Inspect"/></tr></thead><tbody>{positions.map(p => <tr key={p.position_id} className={selected === p.instrument_id ? 'selected-row' : ''} onClick={() => onSelect(p.instrument_id)}><td><button className="instrument-cell" onClick={e => { e.stopPropagation(); onSelect(p.instrument_id); }}><strong>{instrumentName(p.instrument_id)}</strong><span><i className="venue-mark">P</i> Polymarket <b>·</b> {familyName(byId[p.instrument_id].family_id)} <b>·</b> {related(p.instrument_id).length} links</span></button></td><td><Badge tone={p.side === 'YES' ? 'teal' : 'amber'}>{p.side}</Badge></td><td className="mono">{p.quantity.toLocaleString()}</td><td className="mono muted">{price(p.entry_price)}</td><td className="mono">{price(sideMark(p))}</td><td className="mono muted">{money(p.quantity * p.entry_price)}</td><td className={`mono ${markPnl(p) >= 0 ? 'positive' : 'negative'}`}>{money(markPnl(p), true)}</td><td><button className="icon-button" aria-label={`Inspect ${instrumentName(p.instrument_id)}`} onClick={e => { e.stopPropagation(); onInstrument(p.instrument_id); }}><ArrowUpRight size={15}/></button></td></tr>)}</tbody><tfoot><tr><td colSpan={5}>Portfolio total <span className="muted">/ USD</span></td><td className="mono">{money(cost)}</td><td className="mono positive">{money(unrealized, true)}</td><td/></tr></tfoot></table></div>
    <div className="panel-footnote"><span><span className="dot teal"/> All positions mapped to canonical claims</span><button className="text-button" onClick={() => onInstrument(selected)}>Inspect selected instrument <ArrowRight size={13}/></button></div>
  </Panel>
  <Panel title="Terminal scenario matrix" eyebrow="P&L · USD" actions={<button className="text-button" onClick={() => onScenario(0)}>Open Scenario Lab <ArrowUpRight size={13}/></button>}>
    <div className="matrix-subhead"><span>What the portfolio earns when the world resolves.</span><span className="muted">Fixed September: +25 bp</span></div>
    <div className="table-scroll"><table className="matrix-table"><thead><tr><th>Position</th>{presets.map((p, idx) => <th key={p.scenario_id}><button onClick={() => onScenario(idx)}><small>S{String(idx + 1).padStart(2, '0')}</small>{scenarioNames[idx]}<span>{idx === 4 ? 'Pause / Pause +25' : idx === 5 ? 'Terminal vs path' : 'Oct / Dec'}<ArrowUpRight size={10}/></span></button></th>)}</tr></thead><tbody>{positions.map((p, idx) => <tr key={p.position_id} className={selected === p.instrument_id ? 'matrix-selected' : ''}><th><button onClick={() => onSelect(p.instrument_id)}>{byId[p.instrument_id].short_name}<small>{p.side} · {(p.quantity / 1000).toFixed(0)}k</small></button></th>{results.map((r, n) => <td key={n} className={r.rows[idx].pnl >= 0 ? 'profit-cell' : 'loss-cell'}>{compact(r.rows[idx].pnl)}</td>)}</tr>)}</tbody><tfoot><tr><th>Total terminal P&L</th>{results.map((r, n) => <td key={n} className={r.pnl >= 0 ? 'positive' : 'negative'}>{compact(r.pnl)}</td>)}</tr></tfoot></table></div>
    <div className="scenario-bars">{results.map((r, idx) => <button key={idx} onClick={() => onScenario(idx)} aria-label={`Explore ${presets[idx].name}`}><span>S0{idx + 1}</span><div><i className={r.pnl >= 0 ? 'up' : 'down'} style={{ width: `${Math.abs(r.pnl) / Math.max(...results.map(v => Math.abs(v.pnl))) * 100}%` }}/></div><span className={r.pnl >= 0 ? 'positive' : 'negative'}>{compact(r.pnl)}</span></button>)}</div>
    <div className="panel-footnote"><span>Terminal payout − entry cost. Fees excluded.</span><span>Curated scenarios; not exhaustive risk bounds.</span></div>
  </Panel>
  <div className="insight-banner"><div className="insight-icon"><CheckCheck size={22}/></div><div><span className="eyebrow">THE SETTLEMENT DIFFERENCE</span><h3>Same scheduled path. Different payout.</h3><p>An emergency hike leaves the scheduled path unchanged, but flips “Another Hike” to YES.</p></div><button className="secondary-button" onClick={() => onScenario(4)}>Explore the difference <ArrowRight size={15}/></button></div>
  </div><aside className="secondary-column">{graphVisible && <RelationshipGraph selected={selected} onSelect={onSelect} onInspect={onRelationship} onExpand={onRelationships}/>}{checksVisible && <StructuralChecks onInspect={onRelationship}/>}</aside></div></>;
}
export function StructuralChecks({ onInspect }: { onInspect: (id: string) => void }) {
  return <Panel title="Structural checks" eyebrow="FROZEN MARKS"><div className="checks-list">{structuralChecks().map(c => <button key={c.id} className="check-row" onClick={() => onInspect(c.id)}><span className={`check-symbol ${c.kind === 'STRUCTURAL RESIDUAL' ? 'amber-text' : 'positive'}`}>{c.kind === 'STRUCTURAL RESIDUAL' ? 'Δ' : '↳'}</span><div><strong>{c.title}</strong><small>{c.kind}</small></div><span className={`mono ${c.kind === 'STRUCTURAL RESIDUAL' ? 'amber-text' : 'positive'}`}>{c.delta > 0 ? '+' : ''}{c.delta.toFixed(1)}<small> pp</small></span><ArrowUpRight size={12} className="muted"/></button>)}</div><div className="checks-note">Price residuals reflect quoted marks, rounding and spreads. They are not executable arbitrage.</div></Panel>;
}
