import { ArrowRight, RotateCcw, FlaskConical, Check, Info } from 'lucide-react';
import { Panel, Badge } from './primitives';
import { data, byId, presets, buckets, bucketLabels, facts, portfolio, relationships, relationshipHolds, instrumentName, money, price } from '../domain/engine';
import type { Scenario, Bucket, Position } from '../domain/engine';
import { useState } from 'react';

export function ScenarioLab({ state, setState, onInstrument, onRelationship }: { state: Scenario; setState: (s: Scenario) => void; onInstrument: (id: string) => void; onRelationship: (id: string) => void }) {
  const [proposed, setProposed] = useState(false);
  const result = portfolio(state), f = facts(state);
  const active = presets.findIndex(p => JSON.stringify(p.state) === JSON.stringify(state));
  const trade: Position = { position_id: 'proposed', instrument_id: 'ins_another_hike', side: 'YES', quantity: 50000, entry_price: byId.ins_another_hike.snapshot_mark };
  const after = portfolio(state, [...data.portfolio.positions, trade]);
  const selectedResult = proposed ? after : result;
  return <div className="scenario-layout"><aside className="scenario-controls"><Panel title="Build a world" eyebrow="SCENARIO INPUTS" actions={<button className="icon-button" aria-label="Reset scenario" onClick={() => { setState(presets[0].state); setProposed(false); }}><RotateCcw size={14}/></button>}><div className="controls-body"><label className="field-label">CURATED SCENARIOS</label><div className="preset-list">{presets.map((p, idx) => <button className={active === idx ? 'active' : ''} key={p.scenario_id} onClick={() => setState(p.state)}><span className="mono">0{idx + 1}</span><span>{p.name}</span>{active === idx && <Check size={13}/>}</button>)}<button className={state.post_dec_meeting_hike_units_through_dec31 > 0 ? 'active' : ''} onClick={() => setState({ ...presets[3].state, post_dec_meeting_hike_units_through_dec31: 1 })}><span className="mono">07</span><span>After the window closes</span><Badge tone="amber">BASIS</Badge></button></div><div className="control-divider"/><label className="field-label" htmlFor="october">OCTOBER SCHEDULED ACTION</label><select id="october" value={state.october_change_bucket} onChange={e => setState({ ...state, october_change_bucket: e.target.value as Bucket })}>{buckets.map(b => <option key={b} value={b}>{bucketLabels[b]}</option>)}</select><label className="field-label" htmlFor="december">DECEMBER SCHEDULED ACTION</label><select id="december" value={state.december_change_bucket} onChange={e => setState({ ...state, december_change_bucket: e.target.value as Bucket })}>{buckets.map(b => <option key={b} value={b}>{bucketLabels[b]}</option>)}</select><label className="switch-label"><span>Emergency hike before October<small>+25 bp · inside Another Hike window</small></span><input type="checkbox" role="switch" checked={state.emergency_hike_sep17_through_dec_meeting} onChange={e => setState({ ...state, emergency_hike_sep17_through_dec_meeting: e.target.checked })}/></label><label className="field-label" htmlFor="post">POST-MEETING HIKE UNITS</label><div className="range-control"><input id="post" type="range" min="0" max="6" step="1" value={state.post_dec_meeting_hike_units_through_dec31} onChange={e => setState({ ...state, post_dec_meeting_hike_units_through_dec31: Number(e.target.value) })}/><output htmlFor="post">{state.post_dec_meeting_hike_units_through_dec31} × 25 bp</output></div><p className="quiet-copy">Occurs on Dec 10 in this model, before both Dec 31 deadlines.</p></div></Panel></aside>
  <div className="scenario-results"><div className="scenario-result-heading"><div><span className="eyebrow"><FlaskConical size={13}/> {active >= 0 ? `SCENARIO 0${active + 1}` : 'CUSTOM SCENARIO'}</span><h2>{active >= 0 ? presets[active].name : 'Your modeled rate path'}</h2></div><Badge tone="teal">RECALCULATED LOCALLY</Badge></div>
    <div className="scenario-metrics" aria-live="polite"><div><span>TERMINAL PAYOUT</span><strong>{money(selectedResult.payout)}</strong></div><div><span>ENTRY COST</span><strong>{money(selectedResult.cost)}</strong></div><div><span>TERMINAL P&L</span><strong className={selectedResult.pnl >= 0 ? 'positive' : 'negative'}>{money(selectedResult.pnl, true)}</strong></div><div><span>AFTER DECEMBER MEETING</span><strong>{(f.terminal / 100).toFixed(2)}<em>%</em></strong></div></div>
    <Panel title="From actions to outcomes" eyebrow="EXPLICIT TRAJECTORY"><div className="rate-timeline">{[ ['September', 'Fixed baseline', f.path[0]], ['Emergency', state.emergency_hike_sep17_through_dec_meeting ? '+25 bp' : 'No action', f.path[1]], ['October', bucketLabels[state.october_change_bucket], f.path[2]], ['December', bucketLabels[state.december_change_bucket], f.path[3]], ['December 10', `+${state.post_dec_meeting_hike_units_through_dec31 * 25} bp`, f.path[3] + state.post_dec_meeting_hike_units_through_dec31 * 25] ].map(([name, action, value], idx) => <div key={name}><span>{name}</span><strong>{(Number(value) / 100).toFixed(2)}<em>%</em></strong><small>{action}</small>{idx < 4 && <ArrowRight size={15}/>}</div>)}</div></Panel>
    {(state.emergency_hike_sep17_through_dec_meeting || state.post_dec_meeting_hike_units_through_dec31 > 0 || f.max > f.terminal) && <div className="basis-notice"><Info size={19}/><div><strong>Settlement basis, made visible.</strong><p>{state.post_dec_meeting_hike_units_through_dec31 > 0 ? `Annual count includes the December 10 move (${f.annual} units). Another Hike already closed after the December meeting and pays ${f.another ? 'YES' : 'NO'}.` : state.emergency_hike_sep17_through_dec_meeting ? `Scheduled path stays ${f.scheduledPath}; the emergency move still triggers Another Hike.` : `The path reaches ${(f.max / 100).toFixed(2)}%, but the December terminal rate is ${(f.terminal / 100).toFixed(2)}%. A threshold hit is not a terminal rate.`}</p></div></div>}
    <Panel title="Position contributions" eyebrow={proposed ? 'WITH PROPOSED TRADE' : 'CURRENT PORTFOLIO'}><div className="table-scroll"><table><thead><tr><th>Instrument</th><th>Held side</th><th>YES truth</th><th>Payout</th><th>Entry cost</th><th>Terminal P&L</th></tr></thead><tbody>{selectedResult.rows.map(p => <tr key={p.position_id} className={p.position_id === 'proposed' ? 'selected-row' : ''}><td><button className="text-button" onClick={() => onInstrument(p.instrument_id)}>{instrumentName(p.instrument_id)}{p.position_id === 'proposed' && <Badge tone="amber">PROPOSED</Badge>}</button></td><td><Badge tone={p.side === 'YES' ? 'teal' : 'amber'}>{p.side}</Badge></td><td><span className={result.truth[p.instrument_id] ? 'positive' : 'muted'}>{result.truth[p.instrument_id] ? 'TRUE' : 'FALSE'}</span></td><td className="mono">{money(p.payout)}</td><td className="mono muted">{money(p.cost)}</td><td className={`mono ${p.pnl >= 0 ? 'positive' : 'negative'}`}>{money(p.pnl, true)}</td></tr>)}</tbody></table></div></Panel>
    <div className="trade-panel"><div><Badge tone="amber">PROPOSED TRADE</Badge><h3>Buy 50,000 YES · Another Hike <span className="mono muted">@ {price(trade.entry_price)}</span></h3><p>Capital required {money(trade.quantity * trade.entry_price)} · Scenario P&L change <span className={after.pnl - result.pnl >= 0 ? 'positive' : 'negative'}>{money(after.pnl - result.pnl, true)}</span></p></div><label className="switch-label"><span>Include trade</span><input type="checkbox" role="switch" checked={proposed} onChange={e => setProposed(e.target.checked)}/></label></div>
    <Panel title="Constraint evaluation" eyebrow="THIS SCENARIO"><div className="constraint-chips">{relationships.filter(r => r.label !== 'PARTITION').map(r => <button key={r.id} onClick={() => onRelationship(r.id)}><Check size={12} className="positive"/><span>{r.expression}</span><Badge>{relationshipHolds(r, result.truth) ? 'HOLDS' : 'FAILS'}{result.truth[r.ids[0]] === 0 && r.label === 'IMPLIES' ? ' · ANTECEDENT FALSE' : ''}</Badge></button>)}</div></Panel>
    <details className="model-assumptions"><summary>Model scope & assumptions</summary><p>These are representative trajectories, not an exhaustive joint basis for the three families. September is fixed at 4.00% and one annual hike unit. Tail buckets use exactly ±50 bp; the emergency toggle adds +25 bp before October; all post-meeting units occur on December 10; other moves are absent. December's scheduled decision occurs, so the year-end fallback is not modeled. The rate-hit history begins at the supplied 4.00% baseline; no earlier qualifying hit is modeled. No probability is assigned to scenarios. P&L excludes fees, financing and slippage. Proposed-trade impact is a simulation.</p></details>
  </div></div>;
}
